### ISSUE TITLE
Why with interpolation the speed is slower than without it?

### ISSUE THREAD

**Issue by CRquantum** [princemahajan/FLINT#10]
Hi @princemahajan bro,

Not an issue actually. Just a quick question, a lazy question. Sorry about that.
In your flint page you said, eg, For Two-Body circular Earth orbit,
Using DOP853 the time is 0.42s.
However, with interpolation the time is 4.3s.
May I ask, why with interpolation it is 10 times slower?
Thanks.

Best regards,
Rong

**Comment by princemahajan** [comment]
Hi, I think you are referring to the very old results in the FLINT readme. There are lots of modifications gone into the core and test codes after those initial tests. Check the latest results for the CR3BP case (three-body orbit) in the tests folder.

In my CR3BP test script, I actually call Integrate and Interpolate routines in the timed loop. In actual use, you would call Integrate once and call Interpolate afterwards as many times as needed for finding solutions at different grid points (as long as the initial and final times are not changed). Interpolate routine is much faster than Integrate routine because the interpolation coefficients are all pre-computed during the Integrate call.

**Comment by CRquantum** [comment]
I see! Thanks brother! That make sense.
